### ISSUE TITLE
Parse cube shape from knossos conf

### ISSUE THREAD

**Issue by hash-ir** [knossos-project/knossos_utils#26]
Hi,

I initialize a `KnossosDataset` from a `knossos.conf` file. Ideally, the cube shape should be set in the initialization (either constructor or from the conf file [here](https://github.com/knossos-project/knossos_utils/blob/18a27d7ae923ab255f51a6285ab0399ac99e87e2/knossos_utils/knossosdataset.py#L671)). 

In my case, I wrote a script to write a segmentation dataset in the knossos format but later found out that the cube shape was set to the default (128) https://github.com/knossos-project/knossos_utils/blob/18a27d7ae923ab255f51a6285ab0399ac99e87e2/knossos_utils/knossosdataset.py#L306

If you think this makes sense, I can submit a pull request. Happy to discuss this!

**Comment by Optiligence** [comment]
if you are interested in doing a pull request, go ahead

otherwise i could also quickly make a change

But i’m not sure what exactly the issue you are facing is. 
Did you have a segmentation with a different cube shape and the `KnossosDataset` meta data was therefore incorrect? 
Historically, `knossos.conf` did never really support specifying a cube shape other than 128³
At the moment (with the KNOSSOS nightly) we primarily work with `.pyk.conf` which we want to transition to `.toml`. 
It wont hurt adding `cube_edge_length` to `knossos.conf` parsing though.
